"""Single Treasury bond pricing: cash flows, accrued interest, clean and dirty.

This module turns one Treasury (coupon rate, maturity date) plus a bootstrapped
curve into a price. The finance is deliberately explicit because the ordering of
the steps is a classic source of error.

THE ORDER THAT MATTERS
1. Build the semiannual cash flow schedule by stepping BACK from maturity.
2. Discount every FUTURE cash flow off the curve. The sum is the DIRTY price.
   Discounting cash flows always yields the dirty price, never the clean price,
   because the next coupon is discounted in full while in reality the buyer only
   owns part of it.
3. Accrued interest is the portion of the current coupon the seller has earned.
4. clean = dirty - accrued. This subtraction is the only correct direction.

DAY COUNT
US Treasury notes and bonds use actual/actual (ICMA): accrued interest is the
actual number of days from the last coupon to settlement divided by the actual
number of days in the current coupon period, times the coupon amount. We use the
valuation date as the settlement date for this end-of-day tool.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date

from dateutil.relativedelta import relativedelta

from . import etf_config
from .curve import TreasuryCurve


@dataclass
class Bond:
    """A US Treasury note or bond.

    coupon is the annual coupon rate as a decimal (0.04 means a 4% coupon paying
    2.0 per 100 face each half year). maturity is the redemption date.
    """

    cusip: str
    coupon: float
    maturity: date
    name: str = ""


@dataclass
class PricedBond:
    """The output of pricing one bond as of a valuation date.

    All prices are per 100 face value. The same accrued interest applies to bid,
    mid, and ask because the bid/ask is modelled purely as a clean-price spread.
    """

    cusip: str
    clean_bid: float
    clean_mid: float
    clean_ask: float
    accrued_interest: float
    dirty_bid: float
    dirty_mid: float
    dirty_ask: float
    source: str


def coupon_schedule(maturity: date, valuation_date: date) -> list[date]:
    """Return the future coupon dates on or after the valuation date.

    US Treasuries pay semiannually, so coupon dates are generated by stepping back
    six months from maturity. We step back until we are at or before the
    valuation date, then return every generated date strictly after the valuation
    date (those are the remaining cash flows). The maturity date itself is always
    included as the final coupon and principal date.
    """
    dates: list[date] = []
    step = relativedelta(months=12 // etf_config.COUPONS_PER_YEAR)
    current = maturity
    # Walk back far enough to cover the period bracketing the valuation date.
    while current > valuation_date:
        dates.append(current)
        current = current - step
    # current is now the last coupon date on or before the valuation date.
    dates.sort()
    return dates


def previous_coupon_date(maturity: date, valuation_date: date) -> date:
    """Return the most recent coupon date on or before the valuation date.

    This is the start of the current coupon period, used as the accrual start for
    the actual/actual day count.
    """
    step = relativedelta(months=12 // etf_config.COUPONS_PER_YEAR)
    current = maturity
    while current > valuation_date:
        current = current - step
    return current


def accrued_interest(bond: Bond, valuation_date: date) -> float:
    """Compute accrued interest per 100 face using actual/actual (Treasury).

    accrued = (coupon / 2) * (actual days from last coupon to valuation)
                            / (actual days in the current coupon period)

    The numerator is days already elapsed in the period; the denominator is the
    full length of the period the next coupon covers. Per 100 face.
    """
    last_coupon = previous_coupon_date(bond.maturity, valuation_date)
    next_coupon = last_coupon + relativedelta(months=12 // etf_config.COUPONS_PER_YEAR)
    days_elapsed = (valuation_date - last_coupon).days
    days_in_period = (next_coupon - last_coupon).days
    if days_in_period == 0:
        return 0.0
    coupon_amount = bond.coupon / etf_config.COUPONS_PER_YEAR * 100.0
    return coupon_amount * days_elapsed / days_in_period


def year_fraction(valuation_date: date, cash_flow_date: date) -> float:
    """Time from valuation to a cash flow in years, actual/365.

    Used only to look the discount factor up on the curve. The actual/365 basis
    here is a time-to-cashflow measure for discounting and is independent of the
    actual/actual basis used for accrued interest.
    """
    return (cash_flow_date - valuation_date).days / 365.0


def price_bond(
    bond: Bond,
    curve: TreasuryCurve,
    valuation_date: date,
    half_spread_price: float = etf_config.TREASURY_HALF_SPREAD_PRICE,
    source: str = "curve",
) -> PricedBond:
    """Price one Treasury off the bootstrapped curve.

    Procedure, in the order that matters:

    1. Build the remaining coupon cash flows (coupon / 2 per 100 each), with the
       100 principal added to the final maturity cash flow.
    2. Discount each future cash flow by the curve discount factor for its time to
       payment. The sum is the DIRTY mid price per 100 face.
    3. Compute accrued interest (actual/actual) and set clean_mid = dirty_mid
       minus accrued.
    4. Model bid/ask by widening the CLEAN price symmetrically by the configured
       half-spread (a modelled assumption, not a quote), then add the same accrued
       back to recover the dirty bid and ask.

    Returns a PricedBond with clean and dirty bid/mid/ask and the accrued.
    """
    schedule = coupon_schedule(bond.maturity, valuation_date)
    coupon_amount = bond.coupon / etf_config.COUPONS_PER_YEAR * 100.0

    dirty_mid = 0.0
    for i, cf_date in enumerate(schedule):
        t = year_fraction(valuation_date, cf_date)
        cash_flow = coupon_amount
        if i == len(schedule) - 1:
            cash_flow += 100.0  # principal repaid with the final coupon
        dirty_mid += cash_flow * curve.discount_factor(t)

    accrued = accrued_interest(bond, valuation_date)
    clean_mid = dirty_mid - accrued

    clean_bid = clean_mid - half_spread_price
    clean_ask = clean_mid + half_spread_price

    return PricedBond(
        cusip=bond.cusip,
        clean_bid=clean_bid,
        clean_mid=clean_mid,
        clean_ask=clean_ask,
        accrued_interest=accrued,
        dirty_bid=clean_bid + accrued,
        dirty_mid=clean_mid + accrued,
        dirty_ask=clean_ask + accrued,
        source=source,
    )


if __name__ == "__main__":
    # Hand check: price a 4% 5-year Treasury off a synthetic flat 4% curve. On a
    # flat curve at the coupon rate the clean price should sit very close to par.
    from rich.console import Console

    from .curve import bootstrap_zero_curve

    console = Console()
    flat_par = {t: 0.04 for t in (0.5, 1.0, 2.0, 3.0, 5.0, 7.0, 10.0)}
    curve = bootstrap_zero_curve(flat_par, date(2026, 6, 1))
    bond = Bond(cusip="TEST", coupon=0.04, maturity=date(2031, 6, 1), name="4% 2031")
    priced = price_bond(bond, curve, date(2026, 6, 1))
    console.rule("[bold]Bond pricing hand check[/bold]")
    console.log(f"clean_mid {priced.clean_mid:.6f} (expect approx 100 on a flat par curve)")
    console.log(f"accrued   {priced.accrued_interest:.6f}")
    console.log(f"dirty_mid {priced.dirty_mid:.6f}")
